### ISSUE TITLE
vscode mypy doesn't respect `tool.mypy` table in pyproject.toml

### ISSUE THREAD

**Issue by Ravencentric** [matangover/mypy-vscode#99]
```toml
[tool.poetry]
name = "sampleproject"
version = "0.1.0"
description = ""
authors = ["Ravencentric <78981416+Ravencentric@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "sampleproject", from = "src"}]

[tool.poetry.dependencies]
python = "^3.12"
mypy = "^1.11.1"

[tool.mypy]
strict = true
pretty = true
exclude = "tests/"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
![image](https://github.com/user-attachments/assets/279e6737-7c0a-448d-b5d5-3d1210f77eab)
VS Code's mypy complaints about type-hints in `tests/a.py` while `mypy` cli passes with no issues
